# Generated by Django 3.2.1 on 2021-08-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_favourite_like_payorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='belong_art',
            new_name='belong',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='belong_art',
            new_name='belong',
        ),
    ]
